export const SOFTWARE_ECOSYSTEM_MAP: Record<string, string> = {
  node: 'npm',
  npm: 'npm',
  yarn: 'npm',
  pnpm: 'npm',
  python: 'PyPI',
  python3: 'PyPI',
  pip: 'PyPI',
  java: 'Maven',
  mvn: 'Maven',
  gradle: 'Maven',
  postgresql: 'npm',
  mysql: 'npm',
  mariadb: 'npm',
  mongodb: 'npm',
  redis: 'npm',
  sqlite: 'npm',
  pgadmin: 'npm',
}
